package githuberrordialog

import (
	"fmt"
	"net/url"
	"runtime"

	"github.com/gotk3/gotk3/gtk"
)

var (
	//Repository defines the repository that the errordialog should offer a report-issue link to.
	Repository string
	//IssueTemplateEnabled decides wether a prefilled issue template will be included in the report-issue link.
	IssueTemplateEnabled bool
)

const defaultIssueTemplate = `
<!-- This is an autogenerated issue template, please fill in the form below-->
## What did you do when the error occurred?

**FILL IN**

## Error Message

%s

## Machine Information

OS: %s
GOARCH: %s
GTK: %s

## Aditional Information

FILL IN IF PRESENT
`

//CreateIssueURL creates a URL leading you to the "New Issue"-page of UwUNote with a prefilled issue title and body.
func CreateIssueURL(repository, errorMessage string) string {
	gtkVersion := fmt.Sprintf("%d.%d.%d", gtk.GetMajorVersion(), gtk.GetMinorVersion(), gtk.GetMicroVersion())
	issueTemplateFilled := fmt.Sprintf(defaultIssueTemplate, errorMessage, runtime.GOOS, runtime.GOARCH, gtkVersion)

	var linkFragment string
	if IssueTemplateEnabled {
		linkFragment = fmt.Sprintf("?title=%s&body=%s", url.QueryEscape(errorMessage), url.QueryEscape(issueTemplateFilled))
	} else {
		linkFragment = ""
	}

	return "https://" + repository + "/issues/new" + linkFragment
}
